/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expertos;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import net.sf.clipsrules.jni.Environment;
import net.sf.clipsrules.jni.FactAddressValue;
import net.sf.clipsrules.jni.MultifieldValue;
/**
 *
 * @author Stalin Chiguano
 */
public class Ventana extends javax.swing.JFrame {
    private Environment clips;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        
       initComponents();
       clips= new Environment ();
       clips.load("reglas.CLP");
       this.setResizable(false);
       this.setLocationRelativeTo(null);
       this.setIconImage (new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel_licencia = new javax.swing.JLabel();
        jlabel_tipo = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox<>();
        jcb_licencia = new javax.swing.JComboBox<>();
        jcb_so = new javax.swing.JComboBox<>();
        jlabel_so = new javax.swing.JLabel();
        jlabel_recomendar = new javax.swing.JButton();
        jlabel_titulo = new javax.swing.JLabel();
        jl_recomendacion = new javax.swing.JLabel();
        jlabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recomendar Software");
        setBackground(new java.awt.Color(51, 51, 255));
        setForeground(new java.awt.Color(51, 51, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_licencia.setBackground(new java.awt.Color(0, 0, 0));
        jlabel_licencia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabel_licencia.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_licencia.setText("Licencia:");
        getContentPane().add(jlabel_licencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 30));

        jlabel_tipo.setBackground(new java.awt.Color(0, 0, 102));
        jlabel_tipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabel_tipo.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_tipo.setText("Tipo Software:");
        getContentPane().add(jlabel_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, -1));

        jcb_tipo.setBackground(new java.awt.Color(0, 0, 102));
        jcb_tipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcb_tipo.setForeground(new java.awt.Color(255, 255, 255));
        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software_matematico", "Arquitectura", "Sistema_experto", "Edicion_fotografica", "Edicion_vectorial", "Modelado_3d" }));
        jcb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 54, 138, -1));

        jcb_licencia.setBackground(new java.awt.Color(0, 0, 153));
        jcb_licencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcb_licencia.setForeground(new java.awt.Color(255, 255, 255));
        jcb_licencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Privativo", "GNU" }));
        getContentPane().add(jcb_licencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 117, 138, -1));

        jcb_so.setBackground(new java.awt.Color(0, 0, 102));
        jcb_so.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcb_so.setForeground(new java.awt.Color(255, 255, 255));
        jcb_so.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Windows", "Linux" }));
        getContentPane().add(jcb_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 171, 138, -1));

        jlabel_so.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabel_so.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_so.setText("Sistema Operativo:");
        getContentPane().add(jlabel_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jlabel_recomendar.setBackground(new java.awt.Color(0, 0, 153));
        jlabel_recomendar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel_recomendar.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_recomendar.setText("RECOMIENDAME");
        jlabel_recomendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabel_recomendarActionPerformed(evt);
            }
        });
        getContentPane().add(jlabel_recomendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 223, -1, -1));

        jlabel_titulo.setBackground(new java.awt.Color(255, 255, 255));
        jlabel_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabel_titulo.setForeground(new java.awt.Color(255, 51, 51));
        jlabel_titulo.setText("Recomendacion de Software");
        getContentPane().add(jlabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 260, 40));

        jl_recomendacion.setBackground(new java.awt.Color(51, 51, 255));
        jl_recomendacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_recomendacion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jl_recomendacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 390, 29));

        jlabel_fondo.setBackground(new java.awt.Color(255, 255, 255));
        jlabel_fondo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlabel_fondo.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jlabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_recomendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabel_recomendarActionPerformed
        // TODO add your handling code here:
        String hecho,tipo,licencia,so,licencia2 = "";
        tipo=jcb_tipo.getSelectedItem().toString().toLowerCase();
        licencia=jcb_licencia.getSelectedItem().toString();
        so=jcb_so.getSelectedItem().toString().toLowerCase();
        if (licencia.equals("GNU")) {
            licencia2=licencia;
        }
        if (licencia.equals("Privativo")) {
            licencia2=licencia.toLowerCase();
        }
        hecho = "(assert" +
        "(lenguaje-programacion" +
        "(tipo " + tipo + ")" +
        "(licencia " + licencia2 +")" +
        "(so " + so + ")))";
        clips.eval(hecho);
        clips.run();        
        String evaluador = "(find-all-facts ((?m recomendacion)) TRUE)";
        
        FactAddressValue fv = (FactAddressValue) ((MultifieldValue) clips.eval(evaluador)).get(0);
        
        try {
            String msj = fv.getFactSlot("mensaje").toString();
            jl_recomendacion.setText(msj);
            clips.reset();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jlabel_recomendarActionPerformed

    private void jcb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jcb_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
        
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jcb_licencia;
    private javax.swing.JComboBox<String> jcb_so;
    public javax.swing.JComboBox<String> jcb_tipo;
    private javax.swing.JLabel jl_recomendacion;
    private javax.swing.JLabel jlabel_fondo;
    private javax.swing.JLabel jlabel_licencia;
    private javax.swing.JButton jlabel_recomendar;
    private javax.swing.JLabel jlabel_so;
    private javax.swing.JLabel jlabel_tipo;
    private javax.swing.JLabel jlabel_titulo;
    // End of variables declaration//GEN-END:variables
}
